jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install poetry
    displayName: 'Install poetry'
  
  - script: poetry install && poetry develop
    displayName: 'Install dependencies'

  - script: poetry run black --check .
    displayName: 'Check formatting'

  - script: poetry run pytest --cov --junitxml=junit/test-results.xml
    displayName: 'Run pytest'
  
  - script: poetry run codecov
    displayName: 'Upload to codecov'
    env:
      CODECOV_TOKEN: $(codecov.token)

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
