name: Build

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest --cov --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Install black
        run: python -m pip install --upgrade pip black
      - name: Check formatting
        run: black --check .
