name: Build

on: push

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest --cov --cov-report xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.10' }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Install black
        run: python -m pip install --upgrade pip black
      - name: Check formatting
        run: black --check .
